### ISSUE TITLE
Feature Request: Support Helpers

### ISSUE THREAD

**Issue by wormuths** [argaar/comfortable-environment-card#22]
Greetings,

I use the "helper" function to create, for example, "Average Bedroom Temperature" to combine the average of all the temperature sensors in the room.  This integration doesn't allow the helper to be selected as the source for the temperature/humidity, but this would represent the more realistic readings as it combines the measurements from different areas in the room.

Could you allow the integration to select helpers for better accuracy?

Thanks!

**Comment by argaar** [comment]
The editor will show only sensors that match some properties, in fact it will let you choose all sensors that have device class "temperature" (https://github.com/argaar/comfortable-environment-card/blob/81424965cecbaf81cf57e4ca0dd3c6a02fd8c982/src/editor.ts#L59) in the attributes

Could you please check the configuration of your helper to be sure it expose the correct properties?

In the screenshot I've used the helper "template sensor"

![image](https://github.com/argaar/comfortable-environment-card/assets/8555329/bf83ef6e-4308-4c58-b85c-32b8d2c2fb84)

**Comment by argaar** [comment]
Got it, anyway I don't think it should be changed in editor as it presents a (small) list of sensors for a reason.

Can you specify the temperature sensor name via the "Show Code Editor" or (maybe better?) assign the class to the sensor itself via "Developer Tools"->"States" and then add the class as in the screenshot

![image](https://github.com/argaar/comfortable-environment-card/assets/8555329/c634504a-8f1d-440c-8db9-4e18f9d42e0c)

**Comment by wormuths** [comment]
If I manually add the sensor using the Code Editor of the card, it appears to work fine...

So this is just a cosmetic issue for selection of the sensor, but manually putting it in is fine for me.  I'd say if you don't want to have all the "helper" sensors show in the drop-down, maybe just put a note in the information page about helpers needing to be manually entered so nobody else files a bug.  I can't be the only person who uses helpers when we have numerous things reporting temperature and we use the average for more accuracy...

An added benefit of the helper and combined sensors is that if one sensor drops for a minute, it doesn't completely hose the statistics (showing unavailable while offline)...  

Anyway, manually entering is fine with me.  Thanks for the nice work!  It's a simple thing, but it adds a nice visual representation for the overall climate.  I like it.  

Have a great day!

**Comment by argaar** [comment]
@wormuths I understand your (very good) point, and will update the readme asap.

Unfortunately I've no info from HA side (apart the device class) to distinguish between a common sensor and an helper one, so I can't filter by "temperature" and "helpers". 

Not having the filter lead to a too long list of sensors to choose from, and for the user it's just bad

In my opinion this is something HA could improve in the main project, if an helper sensor is created by grouping two or more sensors with the same device_class, it should inherit the same property, or they could let the user choose the device class of the new sensor as for name, units etc...

Will look into the project to see if already exists something addressing this behaviour, otherwise I think it'll worth to open an issue on them
