### ISSUE TITLE
Add a -1 value for the Heat Index?

### ISSUE THREAD

**Issue by igorsantos07** [argaar/comfortable-environment-card#48]
I was just playing around with the new styles and decided to make a card for my **freezer**.

And it says it would be NICE being in -15 celsius, heat-wise?! :joy: 

![image](https://github.com/argaar/comfortable-environment-card/assets/532299/59f12f51-b370-4999-9d3e-2fe65403f440)

So I wonder if there should be an extra -1 value for the Heat Index, for when the scale gets thrown away by extreme temperatures? No clue how the HI is supposed to work with cold values.

**Comment by argaar** [comment]
Well, since it's called "Heat" index, it doesn't work if there's no heat 😄 

To be precise, the math behind is intended for ranges between 25/26C up to 54/55C, values below that treshold meaning there is no "heat" effect, so you could fell warm or cold or whatever but it doesn't affects your body (ok if is -15 maybe it affects but not in terms of "heat").
If you're above 54 you could end up die for too much stress, that's why the gradient start from a "warm" color and ends up in strong red

But you're right, I should put a threshold or "minimum" temp with relative text on it
