### ISSUE TITLE
DI appears stuck on C when sensors are displaying in F

### ISSUE THREAD

**Issue by raindropworks** [argaar/comfortable-environment-card#55]
This may be a dupe of #4 but I seem to be having this problem.  Been using the card for a few weeks now and it works well, I was a bit of a dummy and didn't realize the DI is basically just the 'feels like' temperature because I'm inputting Imperial units but the DI is outputting Metric numbers

**Comment by argaar** [comment]
Hi, the Discomfort Index (or Thom Index) is a value calculated from the themperature expressed in celsius but IS NOT in celsius, nor in fahrenheit, it's just a number from a formula (in the specific case, a formula that works with celsius degree).

What is more like a "feels like" temperature is the Heat Index, but instead of a "universally" fells like, HI it's just useful in a warm/hot environment
