### ISSUE TITLE
Translations do not apply

### ISSUE THREAD

**Issue by GaPhi** [argaar/comfortable-environment-card#7]
The code ```localStorage.getItem('selectedLanguage')``` returns "null"
Then translation always falls back to 'en'.

Is it the good way to get user's language with Home Assistant ?

ChatGPT propose to use hass.language, hass.locale or navigator.language depending on where the code is located...
I do not know what the best is or could be.

**Comment by argaar** [comment]
The navigator.language property should be avoided since it doesn't match HA lang

Looking at the boilerplate project (https://github.com/custom-cards/boilerplate-card/blob/e0402e4c9e2218b7c38dd39680e956e89ca558ed/src/localize/localize.ts#L11C17-L11C57) using the localStorage var seems the good choice in order to evaluate user language.

However I've looked at hass.language and hass.locale.language (that should refelt the setting under System configuration) but for some reason at the moment I can't switch my language, if I try to change it everything remains in English

![image](https://github.com/argaar/comfortable-environment-card/assets/8555329/da9082b7-b9da-40c6-96ba-ad5bc7e5f295)

Need some time to check if is my setup or some bug from HA

**Comment by GaPhi** [comment]
https://github.com/amaximus/garbage-collection-card/blob/e62b2ee2694503bef2b4196e91ec94f941440530/dist/garbage-collection-card.js

It seems a way to get browser language is
```
window.navigator.userLanguage || window.navigator.language;
```

But this is still not hass user setting...

**Comment by argaar** [comment]
@GaPhi I've created many different scenario, tested with Chrome and Firefox, deleted the value from the localStorage and even tried a fresh install of HA, but I've always ended up with that particular variable to be present (or recreated) reflecting the value of the language choosed in my account settings (under the Account->Language).

The only thing I could observe is that the string is not present when I first open the page (maybe in incognito mode) or sometimes, after the deletion, if I don't change the language (probably because it's created/updated only after the dropdown being hit), I really don't know why you missed it on your side.

As of research, the value of hass.locale.language (or hass.language) instead, represent the setting for the whole system (in fact it's under Settings->System->General) so it's wrong to consider that specific value for a frontend since it should respect what the user choosed as a personalization

**Comment by argaar** [comment]
As noted in my previous comment, it seems that the value "selectedLanguage" in localStorage is autogenerated if you switch/choose the language under your Account->Language.

![image](https://github.com/argaar/comfortable-environment-card/assets/8555329/56a58b2a-cc6f-4076-84c2-330eaf7c097f)

Doing this will result in the value being created and the language of the Card, switched to the selected one

**Comment by GaPhi** [comment]
I had to change language and select the wanted one again to get it working.
Probably a cache cleared and not restored by home assistant...
